default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: <%= ENV['db_username'] %>
  password: <%= ENV['db_password'] %>
  host: localhost 

development:
  <<: *default
  database: phototourist_dev

test:
  <<: *default
  database: phototourist_test

production:
  adapter: postgresql
  encoding: unicode
  pool: 5
  url: <%= ENV['DATABASE_URL'] %>
