default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: postgres
  password: superuser
  host: localhost 
  template: template0
  
development:
  <<: *default
  database: phototourist_dev

test:
  <<: *default
  database: phototourist_test

production:
  adapter: postgresql
  encoding: unicode
  pool: 5
  url: <%= ENV['DATABASE_URL'] %>
